### PR TITLE
Enable user defined project directory settings in manifest file

### PR DESCRIPTION
**Pull request by fastner**
This path enable a dict as project kind in manifest file. You can set custom path for class, asset and translation.

### CODE REVIEW

**Comment by fastner** [comment]
Sample for unify:

{
  "name" : "unify",
  "namespace": "unify",
  "kind" : {
    "class" : "source/class/unify",
    "asset" : "source/resource/unify",
    "translation" : "source/translation"
  }
}

**Comment by swernerx** [comment]
Why would you do this? It is already supported in this structure... at least it should be the case.

**Comment by fastner** [comment]
Nope, it generates a class name like unify.unify.ui.widgets.core.Widget.
There is a second unify in the class name that is not correct!

**Comment by swernerx** [comment]
Just reset package to "". Package is automatically set to the projects name and if you have it in your path it duplicated then.

**Comment by fastner** [comment]
Oh okay, that's working :)
So I close the pull request.

**Pull request closed without merging**
